Repository NREL/OpenStudio-HPXML, pull requests merged in 2022-04, with the labels that each got.

#1013 New "End Use: <Fuel>: Heating Heat Pump Backup" output
  BuildResidentialHPXML/measure.xml
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hvac.rb
  ReportSimulationOutput/measure.rb
  ReportSimulationOutput/measure.xml
  ReportSimulationOutput/resources/constants.rb
  ReportSimulationOutput/tests/output_report_test.rb
  docs/source/workflow_outputs.rst
  workflow/tests/base_results/results.csv
  workflow/tests/hpxml_translator_test.rb
Labels: enhancement

#955 Utility bill calculation measure
  .gitignore
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  BuildResidentialScheduleFile/measure.rb
  BuildResidentialScheduleFile/measure.xml
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/constants.rb
  HPXMLtoOpenStudio/resources/meta_measure.rb
  HPXMLtoOpenStudio/resources/output.rb
  README.md
  ReportHPXMLOutput/measure.rb
  ReportHPXMLOutput/measure.xml
  ReportSimulationOutput/measure.rb
  ReportSimulationOutput/measure.xml
  ReportUtilityBills/measure.rb
  ReportUtilityBills/measure.xml
  ReportUtilityBills/resources/Data/UtilityRates/Average_retail_price_of_electricity.csv
  ReportUtilityBills/resources/Data/UtilityRates/HouseholdConsumption.csv
  ReportUtilityBills/resources/Data/UtilityRates/NG_PRI_SUM_A_EPG0_PRS_DMCF_A.csv
  ReportUtilityBills/resources/Data/UtilityRates/PET_PRI_WFR_A_EPD2F_PRS_DPGAL_W.csv
  ReportUtilityBills/resources/Data/UtilityRates/PET_PRI_WFR_A_EPLLPA_PRS_DPGAL_W.csv
  ReportUtilityBills/resources/Data/UtilityRates/README.md
  ReportUtilityBills/resources/util.rb
  ReportUtilityBills/tests/PV_10kW.csv
  ReportUtilityBills/tests/PV_1kW.csv
  ReportUtilityBills/tests/PV_None.csv
  ReportUtilityBills/tests/utility_bills_test.rb
  docs/source/intro.rst
  docs/source/usage_instructions.rst
  docs/source/workflow_outputs.rst
  tasks.rb
  workflow/run_simulation.rb
  workflow/sample_files/base-appliances-oil-location-miami-fl.xml
  workflow/sample_files/base-appliances-propane-location-portland-or.xml
  workflow/template.osw
  workflow/tests/base_results/results.csv
  workflow/tests/base_results/results_bills.csv
  workflow/tests/base_results/results_hvac_sizing.csv
  workflow/tests/hpxml_translator_test.rb
Labels: enhancement

#868 Two boiler approach for combi system
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/constants.rb
  HPXMLtoOpenStudio/resources/waterheater.rb
  HPXMLtoOpenStudio/tests/test_water_heater.rb
  ReportSimulationOutput/measure.rb
  ReportSimulationOutput/measure.xml
  ReportUtilityBills/measure.xml
  workflow/tests/base_results/results.csv
  workflow/tests/base_results/results_bills.csv
Labels: performance, refactor

#1045 Switch to MessagePack
  BuildResidentialHPXML/measure.xml
  Changelog.md
  Gemfile
  Gemfile.lock
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/meta_measure.rb
  HPXMLtoOpenStudio/resources/output.rb
  README.md
  ReportHPXMLOutput/measure.rb
  ReportHPXMLOutput/measure.xml
  ReportSimulationOutput/measure.rb
  ReportSimulationOutput/measure.xml
  ReportUtilityBills/measure.rb
  ReportUtilityBills/measure.xml
  docs/source/intro.rst
  docs/source/usage_instructions.rst
  docs/source/workflow_outputs.rst
  workflow/run_simulation.rb
  workflow/tests/hpxml_translator_test.rb
Labels: performance
