Repository NREL/OpenStudio-HPXML, pull requests merged in 2023-11, with the labels that each got.

#1537 Update undisturbed ground temperatures, try 2
  Changelog.md
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/constructions.rb
  HPXMLtoOpenStudio/resources/data/Xing_okstate_0664D_13659_Table_A-3.csv
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/resources/location.rb
  HPXMLtoOpenStudio/resources/weather.rb
  HPXMLtoOpenStudio/tests/test_enclosure.rb
  HPXMLtoOpenStudio/tests/test_hvac.rb
  HPXMLtoOpenStudio/tests/test_location.rb
  HPXMLtoOpenStudio/tests/test_weather.rb
  workflow/tests/base_results/results_real_homes.csv
  workflow/tests/base_results/results_real_homes_bills.csv
  workflow/tests/base_results/results_sample_files.csv
  workflow/tests/base_results/results_sample_files_bills.csv
Labels: enhancement

#1542 Fix use of hourly msgpack file
  ReportSimulationOutput/measure.rb
  ReportSimulationOutput/measure.xml
Labels: bug

#1541 Balance workflow tests
  Rakefile
  workflow/tests/base_results/results_real_homes.csv
  workflow/tests/base_results/results_real_homes_bills.csv
  workflow/tests/base_results/results_sample_files_bills.csv
  workflow/tests/base_results/results_workflow_simulations1.csv
  workflow/tests/base_results/results_workflow_simulations1_bills.csv
  workflow/tests/base_results/results_workflow_simulations2.csv
  workflow/tests/base_results/results_workflow_simulations2_bills.csv
  workflow/tests/test_ashrae_140.rb
  workflow/tests/test_real_homes.rb
  workflow/tests/test_sample_files.rb
  workflow/tests/test_simulations1.rb
  workflow/tests/test_simulations2.rb
  workflow/tests/util.rb
Labels: refactor

#1526 Adjust sizing for ducted MSHPs
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/resources/output.rb
  HPXMLtoOpenStudio/tests/test_hvac_sizing.rb
  workflow/tests/base_results/results_sizing.csv
  workflow/tests/base_results/results_workflow_simulations1.csv
  workflow/tests/base_results/results_workflow_simulations1_bills.csv
Labels: enhancement

#1544 Fix docs formatting
  docs/source/workflow_inputs.rst
Labels: documentation

#1543 Document default values in BuildResHPXML measure
  BuildResidentialHPXML/README.md
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
Labels: documentation

#1548 Allow crawlspaces/basements with only `Wall`s
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/geometry.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/tests/test_validation.rb
  docs/source/workflow_inputs.rst
  tasks.rb
  workflow/hpxml_inputs.json
  workflow/sample_files/base-foundation-vented-crawlspace-above-grade.xml
  workflow/tests/base_results/results_workflow_simulations1.csv
  workflow/tests/base_results/results_workflow_simulations1_bills.csv
Labels: enhancement

#1317 Heat pump detailed performance inputs
  BuildResidentialHPXML/README.md
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  BuildResidentialHPXML/tests/test_build_residential_hpxml.rb
  Changelog.md
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/resources/util.rb
  HPXMLtoOpenStudio/resources/weather.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  HPXMLtoOpenStudio/tests/test_hvac.rb
  HPXMLtoOpenStudio/tests/test_hvac_sizing.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  docs/source/workflow_inputs.rst
  tasks.rb
  workflow/hpxml_inputs.json
  workflow/sample_files/base-hvac-air-to-air-heat-pump-var-speed-detailed-performance-other-temperatures.xml
  workflow/sample_files/base-hvac-air-to-air-heat-pump-var-speed-detailed-performance.xml
  workflow/sample_files/base-hvac-central-ac-only-var-speed-detailed-performance.xml
  workflow/sample_files/base-hvac-install-quality-air-to-air-heat-pump-var-speed-detailed-performance.xml
  workflow/sample_files/base-hvac-mini-split-air-conditioner-only-ductless-detailed-performance.xml
  workflow/sample_files/base-hvac-mini-split-heat-pump-ducted-detailed-performance.xml
  workflow/sample_files/base-hvac-mini-split-heat-pump-ductless-detailed-performance.xml
  workflow/tests/base_results/results_sizing.csv
  workflow/tests/base_results/results_workflow_simulations1.csv
  workflow/tests/base_results/results_workflow_simulations1_bills.csv
  workflow/tests/base_results/results_workflow_simulations2.csv
  workflow/tests/base_results/results_workflow_simulations2_bills.csv
Labels: enhancement

#1527 Replace HVAC inverse calculations with regressions
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/tests/test_hvac.rb
  workflow/tests/base_results/results_workflow_simulations1.csv
  workflow/tests/base_results/results_workflow_simulations1_bills.csv
  workflow/tests/base_results/results_workflow_simulations2.csv
  workflow/tests/base_results/results_workflow_simulations2_bills.csv
Labels: refactor

#1559 Fix hybrid spelling in docs
  docs/source/workflow_inputs.rst
Labels: documentation
