Repository NREL/OpenStudio-HPXML, pull requests merged in 2023-05, with the labels that each got.

#1371 Allow XMLValidator reuse in validation
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/xmlvalidator.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  tasks.rb
  workflow/tests/hpxml_translator_test.rb
Labels: performance, refactor

#1372 Allow HP backup to be autosized when HP is hardsized
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/tests/test_validation.rb
  workflow/hpxml_inputs.tsv
  workflow/sample_files/base-hvac-air-to-air-heat-pump-1-speed-autosized-backup.xml
  workflow/tests/base_results/results.csv
  workflow/tests/base_results/results_bills.csv
Labels: enhancement

#1378 Replace `hpxml_inputs.tsv` with `hpxml_inputs.json`
  tasks.rb
  workflow/hpxml_inputs.json
  workflow/hpxml_inputs.tsv
Labels: refactor

#1361 Buried ducts
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  Changelog.md
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hpxml_schema/HPXML.xsd
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/tests/test_airflow.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  docs/source/workflow_inputs.rst
  tasks.rb
  workflow/hpxml_inputs.json
  workflow/sample_files/base-hvac-ducts-buried.xml
  workflow/sample_files/base-hvac-ducts-effective-rvalue.xml
  workflow/tests/base_results/results.csv
  workflow/tests/base_results/results_bills.csv
Labels: enhancement

#1379 Infiltration flue enhancements
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/tests/test_defaults.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  docs/source/workflow_inputs.rst
  workflow/hpxml_inputs.json
  workflow/real_homes/house016.xml
  workflow/real_homes/house017.xml
  workflow/real_homes/house019.xml
  workflow/real_homes/house020.xml
  workflow/real_homes/house021.xml
  workflow/real_homes/house022.xml
  workflow/real_homes/house023.xml
  workflow/real_homes/house024.xml
  workflow/real_homes/house025.xml
  workflow/real_homes/house031.xml
  workflow/real_homes/house032.xml
  workflow/real_homes/house033.xml
  workflow/real_homes/house034.xml
  workflow/real_homes/house035.xml
  workflow/real_homes/house036.xml
  workflow/real_homes/house037.xml
  workflow/real_homes/house038.xml
  workflow/real_homes/house039.xml
  workflow/real_homes/house040.xml
  workflow/sample_files/base-enclosure-infil-flue.xml
  workflow/tests/base_results/results.csv
  workflow/tests/base_results/results_bills.csv
Labels: enhancement

#1389 Fix possible SFA/MF error with neighboring buildings
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/geometry.rb
  docs/source/workflow_inputs.rst
  tasks.rb
  workflow/hpxml_inputs.json
  workflow/sample_files/base-misc-neighbor-shading-bldgtype-multifamily.xml
  workflow/tests/base_results/results.csv
  workflow/tests/base_results/results_bills.csv
  workflow/tests/hpxml_translator_test.rb
Labels: bug

#1388 BuildResidentialHPXML: Fix finished attic over garage coordinates
  BuildResidentialHPXML/measure.xml
  BuildResidentialHPXML/resources/geometry.rb
  BuildResidentialHPXML/tests/build_residential_hpxml_test.rb
Labels: bug

#1244 MSHP and ASHP modeling consistency
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/resources/psychrometrics.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  HPXMLtoOpenStudio/tests/test_hvac.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  docs/source/workflow_inputs.rst
  workflow/hpxml_inputs.json
  workflow/sample_files/base-hvac-crankcase-heater-40w.xml
  workflow/tests/base_results/results.csv
  workflow/tests/base_results/results_bills.csv
  workflow/tests/hpxml_translator_test.rb
Labels: refactor

#1394 BuildResidentialHPXML: Allow separate furnace as ductless heat pump backup
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  BuildResidentialHPXML/tests/build_residential_hpxml_test.rb
  workflow/hpxml_inputs.json
  workflow/sample_files/base-hvac-mini-split-heat-pump-ductless-backup-furnace.xml
  workflow/tests/base_results/results.csv
  workflow/tests/base_results/results_bills.csv
Labels: enhancement

#1400 Small psychrometric changes
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/resources/psychrometrics.rb
  HPXMLtoOpenStudio/resources/waterheater.rb
  HPXMLtoOpenStudio/resources/weather.rb
  workflow/tests/base_results/results.csv
  workflow/tests/base_results/results_bills.csv
  workflow/tests/hpxml_translator_test.rb
Labels: refactor

#1399 OS 3.6.1, bump to v1.6.0
  .github/workflows/config.yml
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/version.rb
  docs/source/usage_instructions.rst
Labels: openstudio
