Repository NREL/OpenStudio-HPXML, pull requests merged in 2023-03, with the labels that each got.

#1307 HPXML class cleanup
  BuildResidentialHPXML/measure.xml
  BuildResidentialHPXML/tests/build_residential_hpxml_test.rb
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml.rb
  tasks.rb
  workflow/tests/base_results/results.csv
  workflow/tests/hpxml_translator_test.rb
Labels: refactor

#1318 Code cleanup
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/resources/unit_conversions.rb
  HPXMLtoOpenStudio/resources/waterheater.rb
  HPXMLtoOpenStudio/resources/weather.rb
Labels: refactor

#1319 Misc documentation updates
  docs/source/usage_instructions.rst
  docs/source/workflow_inputs.rst
  docs/source/workflow_outputs.rst
Labels: documentation

#1330 schedules_affected.csv improvements
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/data/schedules_affected.csv
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/resources/schedules.rb
  HPXMLtoOpenStudio/resources/waterheater.rb
Labels: bug, refactor

#1332 Add "System Use" outputs
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  ReportSimulationOutput/measure.rb
  ReportSimulationOutput/measure.xml
  ReportSimulationOutput/tests/output_report_test.rb
  docs/source/workflow_outputs.rst
  workflow/run_simulation.rb
  workflow/template-build-and-run-hpxml-with-stochastic-occupancy.osw
  workflow/template-run-hpxml-with-stochastic-occupancy-subset.osw
  workflow/template-run-hpxml-with-stochastic-occupancy.osw
  workflow/template-run-hpxml.osw
  workflow/tests/base_results/results.csv
Labels: enhancement

#1336 Speed up HPXML files w/ multiple `Building` elements
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  tasks.rb
  workflow/sample_files/base-multiple-buildings.xml
  workflow/tests/hpxml_translator_test.rb
Labels: performance
