Repository NREL/OpenStudio-HPXML, pull requests merged in 2023-10, with the labels that each got.

#1489 Fixes battery resilience output to properly incorporate battery losses
  Changelog.md
  ReportSimulationOutput/measure.rb
  ReportSimulationOutput/measure.xml
  workflow/tests/base_results/results.csv
Labels: bug

#1433 Split battery losses between charging/discharging
  BuildResidentialHPXML/measure.xml
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/battery.rb
  docs/source/workflow_inputs.rst
  workflow/tests/base_results/results.csv
  workflow/tests/base_results/results_bills.csv
Labels: enhancement

#1504 Replace boiler pilot EMS program with new E+ 23.2 capability.
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/constants.rb
  HPXMLtoOpenStudio/resources/hvac.rb
  ReportSimulationOutput/measure.rb
  ReportSimulationOutput/measure.xml
  workflow/tests/base_results/results.csv
  workflow/tests/base_results/results_bills.csv
Labels: refactor

#1386 GSHP Fan/Pump Adjustment
  BuildResidentialHPXML/measure.xml
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/tests/test_hvac.rb
  workflow/tests/base_results/results.csv
  workflow/tests/base_results/results_bills.csv
Labels: bug

#1175 Use E+ 22.2 Incident solar multiplier
  BuildResidentialHPXML/measure.xml
  BuildResidentialScheduleFile/measure.xml
  Changelog.md
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/constants.rb
  HPXMLtoOpenStudio/resources/constructions.rb
  HPXMLtoOpenStudio/resources/energyplus.rb
  HPXMLtoOpenStudio/resources/geometry.rb
  HPXMLtoOpenStudio/resources/simcontrols.rb
  HPXMLtoOpenStudio/tests/test_enclosure.rb
  ReportSimulationOutput/measure.xml
  workflow/tests/base_results/results.csv
  workflow/tests/base_results/results_bills.csv
  workflow/tests/hpxml_translator_test.rb
Labels: bug, performance, refactor

#1475 Update undisturbed ground temperatures
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/resources/psychrometrics.rb
  HPXMLtoOpenStudio/resources/waterheater.rb
  HPXMLtoOpenStudio/resources/weather.rb
  HPXMLtoOpenStudio/tests/test_enclosure.rb
  HPXMLtoOpenStudio/tests/test_weather.rb
  workflow/tests/base_results/results.csv
  workflow/tests/base_results/results_bills.csv
  workflow/tests/base_results/results_sizing.csv
Labels: enhancement

#1524 Mains refactor
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hotwater_appliances.rb
  HPXMLtoOpenStudio/resources/weather.rb
  HPXMLtoOpenStudio/tests/test_weather.rb
Labels: refactor

#1532 Low-flow fixtures enhancement
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hotwater_appliances.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/tests/test_defaults.rb
  HPXMLtoOpenStudio/tests/test_hotwater_appliance.rb
  docs/source/workflow_inputs.rst
  tasks.rb
  workflow/sample_files/base-dhw-low-flow-fixtures.xml
  workflow/tests/base_results/results.csv
  workflow/tests/base_results/results_bills.csv
Labels: enhancement
