Repository NREL/OpenStudio-HPXML, pull requests merged in 2024-06, with the labels that each got.

#1740 Fix furnace heating airflow bug
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/resources/version.rb
  workflow/tests/base_results/results_hers_dse.csv
  workflow/tests/base_results/results_hers_hvac.csv
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
  workflow/tests/base_results/results_sizing.csv
  workflow/tests/util.rb
Labels: bug

#1745 Skylight curbs/shafts
  Changelog.md
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/constructions.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/resources/unit_conversions.rb
  HPXMLtoOpenStudio/tests/test_hvac_sizing.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  docs/source/workflow_inputs.rst
  tasks.rb
  workflow/sample_files/base-enclosure-skylights-cathedral.xml
  workflow/sample_files/base-enclosure-skylights-physical-properties.xml
  workflow/sample_files/base-enclosure-skylights-shading.xml
  workflow/sample_files/base-enclosure-skylights-storms.xml
  workflow/sample_files/base-enclosure-skylights.xml
  workflow/tests/ACCA_Examples/Bell_Residence.xml
  workflow/tests/ACCA_Examples/Smith_Residence.xml
  workflow/tests/ACCA_Examples/Victor_Residence.xml
  workflow/tests/ACCA_Examples/Walker_Residence.xml
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_hvac.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
  workflow/tests/util.rb
Labels: enhancement

#1751 MJ blower fan heat and piping inputs
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hotwater_appliances.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/resources/output.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  HPXMLtoOpenStudio/tests/test_hvac_sizing.rb
  ReportSimulationOutput/measure.xml
  ReportSimulationOutput/tests/test_report_sim_output.rb
  docs/source/workflow_inputs.rst
  docs/source/workflow_outputs.rst
  workflow/tests/ACCA_Examples/Bell_Residence.xml
  workflow/tests/ACCA_Examples/Cobb_Residence.xml
  workflow/tests/ACCA_Examples/Long_Residence.xml
  workflow/tests/ACCA_Examples/Smith_Residence.xml
  workflow/tests/ACCA_Examples/Vatilo_Residence.xml
  workflow/tests/ACCA_Examples/Victor_Residence.xml
  workflow/tests/ACCA_Examples/Walker_Residence.xml
  workflow/tests/base_results/results_simulations_hvac.csv
Labels: enhancement

#1555 ReportUtilityBills: fix calculation of production credits
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/schedule_files/battery.csv
  ReportUtilityBills/measure.rb
  ReportUtilityBills/measure.xml
  ReportUtilityBills/resources/detailed_rates/Sample Time-of-Use Rate High Peak.json
  ReportUtilityBills/resources/util.rb
  ReportUtilityBills/tests/test_report_utility_bills.rb
  workflow/hpxml_inputs.json
  workflow/sample_files/base-misc-bills-battery-scheduled-detailed-only.xml
  workflow/sample_files/base-misc-bills-detailed-only.xml
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_hvac.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
Labels: bug, priority medium
