Repository NREL/OpenStudio-HPXML, pull requests merged in 2024-07, with the labels that each got.

#1660 CFIS w/ AdditionalRuntimeOperatingMode="none"
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  docs/source/workflow_inputs.rst
  tasks.rb
  workflow/hpxml_inputs.json
  workflow/sample_files/base-mechvent-cfis-no-additional-runtime.xml
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_hvac.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
  workflow/tests/base_results/results_workflow_simulations2.csv
  workflow/tests/base_results/results_workflow_simulations2_bills.csv
  workflow/tests/util.rb
Labels: enhancement

#1767 Purge `epw_file` object
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  BuildResidentialScheduleFile/measure.rb
  BuildResidentialScheduleFile/measure.xml
  BuildResidentialScheduleFile/resources/schedules.rb
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/constructions.rb
  HPXMLtoOpenStudio/resources/hotwater_appliances.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/resources/location.rb
  HPXMLtoOpenStudio/resources/schedules.rb
  HPXMLtoOpenStudio/resources/weather.rb
  HPXMLtoOpenStudio/tests/test_location.rb
  HPXMLtoOpenStudio/tests/test_weather.rb
  ReportUtilityBills/measure.xml
  ReportUtilityBills/tests/test_report_utility_bills.rb
Labels: refactor

#1639 Geb HVAC - Onoff thermostat and realistic staging
  BuildResidentialHPXML/README.md
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  Changelog.md
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/energyplus.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/resources/schedules.rb
  HPXMLtoOpenStudio/tests/test_hvac.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  ReportSimulationOutput/measure.rb
  ReportSimulationOutput/measure.xml
  docs/source/workflow_inputs.rst
  workflow/hpxml_inputs.json
  workflow/sample_files/base-hvac-air-to-air-heat-pump-1-speed-lockout-temperatures-research-features.xml
  workflow/sample_files/base-hvac-air-to-air-heat-pump-1-speed-research-features.xml
  workflow/sample_files/base-hvac-air-to-air-heat-pump-2-speed-research-features.xml
  workflow/sample_files/base-hvac-air-to-air-heat-pump-var-speed-research-features.xml
  workflow/sample_files/base-hvac-central-ac-only-2-speed-research-features.xml
  workflow/sample_files/base-hvac-room-ac-only-research-features-detailed-setpoints.xml
  workflow/sample_files/base-hvac-room-ac-only-research-features.xml
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_hvac.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
  workflow/tests/base_results/results_sizing.csv
  workflow/tests/util.rb
Labels: enhancement, priority medium

#1769 Removes capacity ratio from `hvac_sizing.rb`
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
Labels: refactor

#1760 Leakiness Description
  BuildResidentialHPXML/README.md
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/tests/test_airflow.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  HPXMLtoOpenStudio/tests/test_hvac_sizing.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  docs/source/workflow_inputs.rst
  workflow/hpxml_inputs.json
  workflow/sample_files/base-bldgtype-mf-unit-infil-leakiness-description.xml
  workflow/sample_files/base-enclosure-2stories-infil-leakiness-description.xml
  workflow/sample_files/base-enclosure-infil-leakiness-description.xml
  workflow/tests/ACCA_Examples/Bell_Residence.xml
  workflow/tests/ACCA_Examples/Bob_Ross_Residence.xml
  workflow/tests/ACCA_Examples/Cobb_Residence.xml
  workflow/tests/ACCA_Examples/Long_Residence.xml
  workflow/tests/ACCA_Examples/Smith_Residence.xml
  workflow/tests/ACCA_Examples/Vatilo_Residence.xml
  workflow/tests/ACCA_Examples/Victor_Residence.xml
  workflow/tests/ACCA_Examples/Walker_Residence.xml
  workflow/tests/base_results/results_acca_hvac.csv
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_hvac.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
Labels: enhancement

#1770 BuildResidentialScheduleFile: increase minimum cw and dw flow rate
  BuildResidentialScheduleFile/measure.xml
  BuildResidentialScheduleFile/resources/schedules.rb
  Changelog.md
Labels: bug

#1774 Rename slab variables in BuildResidentialHPXML measure
  BuildResidentialHPXML/README.md
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  BuildResidentialHPXML/tests/test_build_residential_hpxml.rb
  Changelog.md
  workflow/hpxml_inputs.json
Labels: refactor

#1771 More ruby documentation
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  BuildResidentialHPXML/resources/geometry.rb
  BuildResidentialHPXML/tests/test_build_residential_hpxml.rb
  BuildResidentialScheduleFile/measure.rb
  BuildResidentialScheduleFile/measure.xml
  BuildResidentialScheduleFile/resources/README.md
  BuildResidentialScheduleFile/resources/schedules.rb
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/battery.rb
  HPXMLtoOpenStudio/resources/constructions.rb
  HPXMLtoOpenStudio/resources/geometry.rb
  HPXMLtoOpenStudio/resources/hotwater_appliances.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/resources/lighting.rb
  HPXMLtoOpenStudio/resources/location.rb
  HPXMLtoOpenStudio/resources/materials.rb
  HPXMLtoOpenStudio/resources/math.rb
  HPXMLtoOpenStudio/resources/meta_measure.rb
  HPXMLtoOpenStudio/resources/misc_loads.rb
  HPXMLtoOpenStudio/resources/psychrometrics.rb
  HPXMLtoOpenStudio/resources/schedules.rb
  HPXMLtoOpenStudio/resources/util.rb
  HPXMLtoOpenStudio/resources/utility_bills.rb
  HPXMLtoOpenStudio/resources/waterheater.rb
  HPXMLtoOpenStudio/resources/weather.rb
  HPXMLtoOpenStudio/resources/xmlvalidator.rb
  HPXMLtoOpenStudio/tests/test_airflow.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  HPXMLtoOpenStudio/tests/test_water_heater.rb
  ReportSimulationOutput/measure.rb
  ReportSimulationOutput/measure.xml
  ReportUtilityBills/measure.rb
  ReportUtilityBills/measure.xml
  ReportUtilityBills/resources/util.rb
  ReportUtilityBills/tests/test_report_utility_bills.rb
  docs/source/workflow_inputs.rst
  tasks.rb
  workflow/tests/base_results/results_simulations_hvac.csv
  workflow/tests/util.rb
Labels: refactor, documentation

#1779 Clarify hot water use outputs
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  docs/source/workflow_outputs.rst
Labels: documentation

#1780 Allow negative `Elevation` values
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml_schema/HPXML.xsd
  HPXMLtoOpenStudio/tests/test_defaults.rb
  docs/source/workflow_inputs.rst
Labels: bug, hpxml

#1783 Fix skylight curb area in Bob Ross test file
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  workflow/tests/ACCA_Examples/Bob_Ross_Residence.xml
  workflow/tests/base_results/results_acca_hvac.csv
Labels: bug
