Repository NREL/OpenStudio-HPXML, pull requests merged in 2024-01, with the labels that each got.

#1577 ANSI 301-2022: Programmable Thermostat
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hvac.rb
Labels: enhancement

#1589 Flatten docs/schematron
  BuildResidentialHPXML/README.md
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/tests/test_validation.rb
  docs/source/workflow_inputs.rst
Labels: documentation

#1590 Revert XMLValidator workaround
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/xmlvalidator.rb
Labels: refactor

#1587 ANSI 301-2022: Shared batteries
  BuildResidentialHPXML/README.md
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  Changelog.md
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/battery.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hpxml_schema/HPXML.xsd
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/tests/test_battery.rb
  ReportSimulationOutput/measure.rb
  ReportSimulationOutput/measure.xml
  docs/source/workflow_inputs.rst
  workflow/hpxml_inputs.json
  workflow/sample_files/base-bldgtype-mf-unit-shared-pv-battery.xml
  workflow/tests/base_results/results_workflow_simulations1.csv
  workflow/tests/base_results/results_workflow_simulations1_bills.csv
Labels: enhancement

#1588 Move appliance inputs validation
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml_schema/HPXML.xsd
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/tests/test_validation.rb
Labels: refactor

#1598 Fix error if emissions scenarios and short run period
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/tests/test_simcontrols.rb
  ReportSimulationOutput/measure.rb
  ReportSimulationOutput/measure.xml
  ReportSimulationOutput/tests/test_report_sim_output.rb
  workflow/hpxml_inputs.json
  workflow/sample_files/base-simcontrol-runperiod-1-month.xml
  workflow/tests/base_results/results_workflow_simulations2.csv
  workflow/tests/base_results/results_workflow_simulations2_bills.csv
  workflow/tests/util.rb
Labels: bug

#1558 Allow autosizing with detailed performance data inputs for var speed systems
  BuildResidentialHPXML/README.md
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  BuildResidentialHPXML/tests/test_build_residential_hpxml.rb
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  docs/source/workflow_inputs.rst
  workflow/hpxml_inputs.json
  workflow/sample_files/base-hvac-air-to-air-heat-pump-var-speed-detailed-performance-autosize.xml
  workflow/sample_files/base-hvac-air-to-air-heat-pump-var-speed-detailed-performance-normalized-capacities.xml
  workflow/sample_files/base-hvac-central-ac-only-var-speed-detailed-performance-autosize.xml
  workflow/sample_files/base-hvac-mini-split-air-conditioner-only-ductless-detailed-performance-autosize.xml
  workflow/sample_files/base-hvac-mini-split-heat-pump-ducted-detailed-performance-autosize.xml
  workflow/sample_files/base-hvac-mini-split-heat-pump-ductless-detailed-performance-autosize.xml
  workflow/tests/base_results/results_workflow_simulations1.csv
  workflow/tests/base_results/results_workflow_simulations1_bills.csv
Labels: enhancement

#1603 Remove global variables from hvac_sizing.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  workflow/tests/base_results/results_sizing.csv
Labels: refactor

#1592 Low-E window improvements
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/constructions.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/tests/test_defaults.rb
  docs/source/workflow_inputs.rst
  tasks.rb
  workflow/sample_files/base-enclosure-windows-physical-properties.xml
  workflow/tests/base_results/results_workflow_simulations2.csv
  workflow/tests/base_results/results_workflow_simulations2_bills.csv
Labels: enhancement

#1604 Allow heating (or cooling) only detailed performance data
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  docs/source/workflow_inputs.rst
  workflow/hpxml_inputs.json
  workflow/sample_files/base-hvac-air-to-air-heat-pump-var-speed-detailed-performance-heating-only.xml
  workflow/tests/base_results/results_workflow_simulations1.csv
  workflow/tests/base_results/results_workflow_simulations1_bills.csv
Labels: enhancement
