Repository NREL/OpenStudio-HPXML, pull requests merged in 2024-10, with the labels that each got.

#1846 Link to resources; fix possible plug/fuel load error
  BuildResidentialHPXML/measure.xml
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/tests/test_validation.rb
  README.md
  ReportUtilityBills/measure.xml
  docs/source/index.rst
  docs/source/resources.rst
  docs/source/workflow_inputs.rst
Labels: bug, documentation

#1849 Stratified tank bugfix
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/waterheater.rb
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
Labels: bug, refactor

#1851 Add schedule methods to model.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/constructions.rb
  HPXMLtoOpenStudio/resources/geometry.rb
  HPXMLtoOpenStudio/resources/hotwater_appliances.rb
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/resources/model.rb
  HPXMLtoOpenStudio/resources/schedules.rb
  HPXMLtoOpenStudio/resources/waterheater.rb
  HPXMLtoOpenStudio/tests/test_schedules.rb
Labels: refactor

#1854 Fix `HeatingPerformanceDataPoint.delete` method
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml.rb
  docs/source/workflow_inputs.rst
Labels: bug

#1855 Some more ruby documentation
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/resources/lighting.rb
  HPXMLtoOpenStudio/resources/misc_loads.rb
  HPXMLtoOpenStudio/resources/xmlhelper.rb
  docs/source/workflow_inputs.rst
Labels: documentation

#1857 HPWH capacity inputs
  BuildResidentialHPXML/README.md
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/defaults.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/resources/unit_conversions.rb
  HPXMLtoOpenStudio/resources/waterheater.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  HPXMLtoOpenStudio/tests/test_water_heater.rb
  docs/source/workflow_inputs.rst
  workflow/hpxml_inputs.json
  workflow/real_homes/house039.xml
  workflow/sample_files/base-dhw-tank-heat-pump-capacities.xml
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_hvac.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
Labels: enhancement

#1863 `HasOutdoorAirControl` input for CFIS systems
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/defaults.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/tests/test_airflow.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  docs/source/workflow_inputs.rst
  tasks.rb
  workflow/hpxml_inputs.json
  workflow/sample_files/base-mechvent-cfis-no-outdoor-air-control.xml
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_hvac.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
Labels: enhancement

#1862 Bugfix for autosizing when detailed performance capacity fractions are provided
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/tests/test_hvac_sizing.rb
Labels: bug

#1865 `SupplementalFanRunsWithAirHandlerFan` input for CFIS systems
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/defaults.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/tests/test_defaults.rb
  docs/source/workflow_inputs.rst
  tasks.rb
  workflow/hpxml_inputs.json
  workflow/sample_files/base-mechvent-cfis-supplemental-fan-exhaust-synchronized.xml
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_hvac.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
Labels: enhancement

#1866 `ControlType` input for CFIS systems
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/defaults.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/tests/test_airflow.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  docs/source/workflow_inputs.rst
  tasks.rb
  workflow/hpxml_inputs.json
  workflow/sample_files/base-mechvent-cfis-control-type-timer.xml
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_hvac.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
Labels: enhancement

#1868 Bugfix for CFIS systems w/ supplemental fan and sub-hourly timesteps
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/constants.rb
  HPXMLtoOpenStudio/tests/test_airflow.rb
  tasks.rb
  workflow/hpxml_inputs.json
  workflow/run_simulation.rb
  workflow/sample_files/base-mechvent-cfis-15-mins.xml
  workflow/sample_files/base-mechvent-cfis-supplemental-fan-exhaust-15-mins.xml
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_hvac.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
Labels: bug, refactor

#1699 Improves window component loads
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/output.rb
  workflow/tests/base_results/results_simulations_loads.csv
Labels: energyplus, priority medium

#1872 Bugfix for results_design_load_details.csv
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/tests/test_hvac_sizing.rb
Labels: bug

#1815 OpenStudio 3.9/EnergyPlus 24.2
  .github/workflows/config.yml
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/location.rb
  HPXMLtoOpenStudio/resources/output.rb
  HPXMLtoOpenStudio/resources/version.rb
  ReportUtilityBills/measure.xml
  ReportUtilityBills/tests/test_report_utility_bills.rb
  docs/source/usage_instructions.rst
  tasks.rb
  workflow/tests/base_results/results_hers_hot_water.csv
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
  workflow/tests/util.rb
Labels: openstudio, energyplus
