Repository NREL/OpenStudio-HPXML, pull requests merged in 2024-03, with the labels that each got.

#1636 Allow building site inputs
  BuildResidentialHPXML/README.md
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  BuildResidentialHPXML/resources/geometry.rb
  BuildResidentialScheduleFile/measure.rb
  BuildResidentialScheduleFile/measure.xml
  BuildResidentialScheduleFile/resources/schedules.rb
  BuildResidentialScheduleFile/tests/test_build_residential_schedule_file.rb
  Changelog.md
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hpxml_schema/HPXML.xsd
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/resources/location.rb
  HPXMLtoOpenStudio/resources/psychrometrics.rb
  HPXMLtoOpenStudio/resources/waterheater.rb
  HPXMLtoOpenStudio/resources/weather.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  HPXMLtoOpenStudio/tests/test_weather.rb
  docs/source/workflow_inputs.rst
  workflow/hpxml_inputs.json
  workflow/sample_files/base-location-detailed.xml
  workflow/tests/ACCA_Examples/Bell_Residence.xml
  workflow/tests/ACCA_Examples/Cobb_Residence.xml
  workflow/tests/ACCA_Examples/Long_Residence.xml
  workflow/tests/ACCA_Examples/Smith_Residence.xml
  workflow/tests/ACCA_Examples/Vatilo_Residence.xml
  workflow/tests/ACCA_Examples/Victor_Residence.xml
  workflow/tests/ACCA_Examples/Walker_Residence.xml
  workflow/tests/base_results/results_sizing.csv
  workflow/tests/base_results/results_workflow_simulations1.csv
  workflow/tests/base_results/results_workflow_simulations1_bills.csv
  workflow/tests/base_results/results_workflow_simulations2.csv
  workflow/tests/base_results/results_workflow_simulations2_bills.csv
  workflow/tests/util.rb
Labels: enhancement

#1637 Improve roof pitch in docs
  docs/source/workflow_inputs.rst
Labels: documentation

#1638 Document capabilities
  README.md
  docs/source/intro.rst
Labels: documentation

#1641 Additional Manual J design condition inputs
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/resources/psychrometrics.rb
  HPXMLtoOpenStudio/resources/weather.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  HPXMLtoOpenStudio/tests/test_hvac_sizing.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  HPXMLtoOpenStudio/tests/test_weather.rb
  docs/source/workflow_inputs.rst
  tasks.rb
  workflow/sample_files/base-hvac-autosize-sizing-controls.xml
  workflow/tests/ACCA_Examples/Bell_Residence.xml
  workflow/tests/ACCA_Examples/Cobb_Residence.xml
  workflow/tests/ACCA_Examples/Long_Residence.xml
  workflow/tests/ACCA_Examples/Smith_Residence.xml
  workflow/tests/ACCA_Examples/Vatilo_Residence.xml
  workflow/tests/ACCA_Examples/Victor_Residence.xml
  workflow/tests/ACCA_Examples/Walker_Residence.xml
  workflow/tests/base_results/results_sizing.csv
  workflow/tests/base_results/results_workflow_simulations1.csv
  workflow/tests/base_results/results_workflow_simulations1_bills.csv
  workflow/tests/base_results/results_workflow_simulations2.csv
  workflow/tests/base_results/results_workflow_simulations2_bills.csv
Labels: enhancement

#1586 ANSI 301-2022: Airflow
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  docs/source/workflow_inputs.rst
  workflow/tests/base_results/results_sizing.csv
  workflow/tests/base_results/results_workflow_simulations1.csv
  workflow/tests/base_results/results_workflow_simulations1_bills.csv
  workflow/tests/base_results/results_workflow_simulations2.csv
  workflow/tests/base_results/results_workflow_simulations2_bills.csv
Labels: enhancement

#1325 Geb HVAC - variable speed systems
  Changelog.md
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/energyplus.rb
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/resources/schedule_files/hvac-variable-system-maximum-power-ratios-varied.csv
  HPXMLtoOpenStudio/resources/schedules.rb
  HPXMLtoOpenStudio/tests/test_hvac.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  HPXMLtoOpenStudio/tests/util.rb
  docs/source/workflow_inputs.rst
  tasks.rb
  workflow/hpxml_inputs.json
  workflow/sample_files/base-hvac-air-to-air-heat-pump-var-speed-max-power-ratio-schedule-10-mins.xml
  workflow/sample_files/base-hvac-air-to-air-heat-pump-var-speed-max-power-ratio-schedule-two-systems.xml
  workflow/sample_files/base-hvac-air-to-air-heat-pump-var-speed-max-power-ratio-schedule.xml
  workflow/sample_files/base-hvac-central-ac-only-var-speed-max-power-ratio-schedule.xml
  workflow/sample_files/base-hvac-furnace-gas-central-ac-var-speed-max-power-ratio-schedule.xml
  workflow/sample_files/base-hvac-mini-split-heat-pump-ducted-heating-only-max-power-ratio-schedule.xml
  workflow/sample_files/base-hvac-mini-split-heat-pump-ducted-max-power-ratio-schedule.xml
  workflow/tests/base_results/results_sizing.csv
  workflow/tests/base_results/results_workflow_simulations1.csv
  workflow/tests/base_results/results_workflow_simulations1_bills.csv
  workflow/tests/util.rb
Labels: enhancement

#1648 Allow appending columns in BuildResidentialScheduleFile measure
  BuildResidentialScheduleFile/README.md
  BuildResidentialScheduleFile/measure.rb
  BuildResidentialScheduleFile/measure.xml
  BuildResidentialScheduleFile/resources/schedules.rb
  BuildResidentialScheduleFile/tests/test_build_residential_schedule_file.rb
  Changelog.md
Labels: enhancement

#1634 Update Other, TV, and Ceiling Fan stochastic schedules
  BuildResidentialHPXML/measure.xml
  BuildResidentialScheduleFile/measure.rb
  BuildResidentialScheduleFile/measure.xml
  BuildResidentialScheduleFile/resources/constants.rb
  BuildResidentialScheduleFile/resources/schedules.rb
  BuildResidentialScheduleFile/tests/test_build_residential_schedule_file.rb
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic-10-mins.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic-30-mins.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic_2.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic_3.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic_4.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic_5.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic_6.csv
  HPXMLtoOpenStudio/tests/test_schedules.rb
  workflow/tests/base_results/results_workflow_simulations1.csv
  workflow/tests/base_results/results_workflow_simulations1_bills.csv
  workflow/tests/base_results/results_workflow_simulations2.csv
  workflow/tests/base_results/results_workflow_simulations2_bills.csv
Labels: enhancement

#1632 Additional design load detailed outputs
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/tests/test_hvac_sizing.rb
  ReportSimulationOutput/measure.rb
  ReportSimulationOutput/measure.xml
  ReportSimulationOutput/tests/test_report_sim_output.rb
  docs/source/workflow_outputs.rst
  workflow/tests/ACCA_Examples/Victor_Residence.xml
  workflow/tests/base_results/results_sizing.csv
  workflow/tests/base_results/results_workflow_simulations1.csv
  workflow/tests/base_results/results_workflow_simulations1_bills.csv
  workflow/tests/base_results/results_workflow_simulations2.csv
  workflow/tests/base_results/results_workflow_simulations2_bills.csv
Labels: enhancement

#1645 ANSI 301-2022 Duct leakage imbalance
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/tests/test_airflow.rb
  workflow/tests/base_results/results_workflow_simulations1.csv
  workflow/tests/base_results/results_workflow_simulations1_bills.csv
  workflow/tests/base_results/results_workflow_simulations2.csv
  workflow/tests/base_results/results_workflow_simulations2_bills.csv
  workflow/tests/util.rb
Labels: enhancement

#1640 RTD: Geometry section of Introduction
  BuildResidentialHPXML/README.md
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  HPXMLtoOpenStudio/measure.xml
  docs/source/images/geometry_3d.png
  docs/source/images/geometry_exploded.png
  docs/source/intro.rst
  docs/source/workflow_inputs.rst
Labels: documentation

#1650 Add `--skip-simulation` argument
  Changelog.md
  workflow/run_simulation.rb
  workflow/tests/test_other.rb
Labels: enhancement

#1651 Allows requesting timeseries outputs with different frequencies
  Changelog.md
  docs/source/usage_instructions.rst
  docs/source/workflow_outputs.rst
  workflow/run_simulation.rb
  workflow/tests/test_other.rb
Labels: enhancement

#1601 ANSI 301-2022: Envelope
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/constructions.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  docs/source/workflow_inputs.rst
  workflow/tests/base_results/results_bills.csv
  workflow/tests/base_results/results_workflow_simulations1.csv
  workflow/tests/base_results/results_workflow_simulations1_bills.csv
  workflow/tests/base_results/results_workflow_simulations2.csv
  workflow/tests/base_results/results_workflow_simulations2_bills.csv
Labels: enhancement

#1665 Remove final HVAC sizing globals
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
Labels: refactor
