Repository NREL/OpenStudio-HPXML, pull requests merged in 2024-02, with the labels that each got.

#1608 Update default VSHP min compressor temperature
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  docs/source/workflow_inputs.rst
  workflow/tests/base_results/results_workflow_simulations1.csv
  workflow/tests/base_results/results_workflow_simulations1_bills.csv
Labels: enhancement

#1597 HP backup sizing methodology
  .gitignore
  BuildResidentialHPXML/README.md
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  HPXMLtoOpenStudio/tests/test_hvac_sizing.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  docs/source/workflow_inputs.rst
  workflow/hpxml_inputs.json
  workflow/real_homes/house047.xml
  workflow/real_homes/house049.xml
  workflow/sample_files/base-hvac-air-to-air-heat-pump-var-speed-autosize-maxload.xml
  workflow/tests/base_results/results_sizing.csv
  workflow/tests/base_results/results_workflow_simulations1.csv
  workflow/tests/base_results/results_workflow_simulations1_bills.csv
  workflow/tests/base_results/results_workflow_simulations2.csv
  workflow/tests/base_results/results_workflow_simulations2_bills.csv
Labels: enhancement

#1620 Remove outdated columns in docs.
  docs/source/workflow_inputs.rst
Labels: bug, documentation

#1609 Alternative ceiling fan watts input
  BuildResidentialHPXML/README.md
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hpxml_schema/HPXML.xsd
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  HPXMLtoOpenStudio/tests/test_hvac.rb
  HPXMLtoOpenStudio/tests/test_lighting.rb
  docs/source/workflow_inputs.rst
  tasks.rb
  workflow/hpxml_inputs.json
  workflow/sample_files/base-lighting-ceiling-fans-label-energy-use.xml
  workflow/tests/base_results/results_workflow_simulations2.csv
  workflow/tests/base_results/results_workflow_simulations2_bills.csv
Labels: enhancement

#1622 BuildResidentialHPXML: multiple vacancy/outage periods
  BuildResidentialHPXML/README.md
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  BuildResidentialHPXML/tests/test_build_residential_hpxml.rb
  Changelog.md
  workflow/hpxml_inputs.json
Labels: enhancement

#1625 Add hot_water_recirculation_pump to unavailable_periods.csv
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/data/unavailable_periods.csv
  HPXMLtoOpenStudio/tests/test_schedules.rb
  ReportSimulationOutput/measure.xml
  ReportSimulationOutput/tests/test_report_sim_output.rb
  tasks.rb
  workflow/hpxml_inputs.json
  workflow/sample_files/base-schedules-simple-power-outage.xml
  workflow/sample_files/base-schedules-simple-vacancy.xml
  workflow/sample_files/base-schedules-simple.xml
  workflow/tests/base_results/results_workflow_simulations2.csv
  workflow/tests/base_results/results_workflow_simulations2_bills.csv
Labels: bug

#1626 Use `AverageCeilingHeight` in natural ACH/CFM calculations
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/tests/test_airflow.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  docs/source/workflow_inputs.rst
  workflow/tests/base_results/results_workflow_simulations1.csv
  workflow/tests/base_results/results_workflow_simulations1_bills.csv
  workflow/tests/base_results/results_workflow_simulations2.csv
  workflow/tests/base_results/results_workflow_simulations2_bills.csv
Labels: enhancement, refactor

#1627 Refactor code related to schedule file columns
  BuildResidentialScheduleFile/measure.xml
  BuildResidentialScheduleFile/resources/schedules.rb
  BuildResidentialScheduleFile/tests/test_build_residential_schedule_file.rb
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/battery.rb
  HPXMLtoOpenStudio/resources/constructions.rb
  HPXMLtoOpenStudio/resources/geometry.rb
  HPXMLtoOpenStudio/resources/hotwater_appliances.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/resources/lighting.rb
  HPXMLtoOpenStudio/resources/misc_loads.rb
  HPXMLtoOpenStudio/resources/schedules.rb
  HPXMLtoOpenStudio/resources/waterheater.rb
  HPXMLtoOpenStudio/tests/test_schedules.rb
  workflow/tests/test_other.rb
Labels: refactor

#1633 Manual J indoor RH improvements
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  docs/source/workflow_inputs.rst
  workflow/tests/base_results/results_sizing.csv
  workflow/tests/base_results/results_workflow_simulations1.csv
  workflow/tests/base_results/results_workflow_simulations1_bills.csv
  workflow/tests/base_results/results_workflow_simulations2.csv
  workflow/tests/base_results/results_workflow_simulations2_bills.csv
Labels: bug, enhancement

#1611 HVAC Autosizing Factors
  BuildResidentialHPXML/README.md
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  HPXMLtoOpenStudio/tests/test_hvac_sizing.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  docs/source/workflow_inputs.rst
  workflow/hpxml_inputs.json
  workflow/sample_files/base-hvac-air-to-air-heat-pump-1-speed-autosize-factor.xml
  workflow/sample_files/base-hvac-air-to-air-heat-pump-var-speed-backup-furnace-autosize-factor.xml
  workflow/sample_files/base-hvac-central-ac-only-1-speed-autosize-factor.xml
  workflow/sample_files/base-hvac-furnace-gas-only-autosize-factor.xml
  workflow/tests/base_results/results_workflow_simulations1.csv
  workflow/tests/base_results/results_workflow_simulations1_bills.csv
Labels: enhancement
