Repository NREL/OpenStudio-HPXML, pull requests merged in 2024-09, with the labels that each got.

#1775 Update plug load end uses for operational calculations
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/misc_loads.rb
  HPXMLtoOpenStudio/tests/test_miscloads.rb
  docs/source/workflow_inputs.rst
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
Labels: enhancement

#1824 Minor refactor of Waterheater.get_default_location method
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/waterheater.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  docs/source/workflow_inputs.rst
Labels: refactor

#1817 More ruby documentation, HPXMLtoOpenStudio/measure.rb refactor
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  BuildResidentialHPXML/resources/geometry.rb
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/battery.rb
  HPXMLtoOpenStudio/resources/constructions.rb
  HPXMLtoOpenStudio/resources/generator.rb
  HPXMLtoOpenStudio/resources/geometry.rb
  HPXMLtoOpenStudio/resources/hotwater_appliances.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/resources/internal_gains.rb
  HPXMLtoOpenStudio/resources/lighting.rb
  HPXMLtoOpenStudio/resources/location.rb
  HPXMLtoOpenStudio/resources/misc_loads.rb
  HPXMLtoOpenStudio/resources/model.rb
  HPXMLtoOpenStudio/resources/output.rb
  HPXMLtoOpenStudio/resources/pv.rb
  HPXMLtoOpenStudio/resources/schedules.rb
  HPXMLtoOpenStudio/resources/waterheater.rb
  HPXMLtoOpenStudio/resources/xmlhelper.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
Labels: refactor, documentation

#1834 Clarify dehumidifier and pool/spa docs
  docs/source/workflow_inputs.rst
Labels: documentation

#1837 Airflow.rb cleanup
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
Labels: refactor

#1825 Fix negative defrost power when applying advanced defrost with small cooling capacity
  BuildResidentialHPXML/measure.xml
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/tests/test_hvac.rb
Labels: bug

#1707 Replace Hard-Coded Sensible Capacity Curves with ADP/BF
  BuildResidentialHPXML/measure.xml
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/geometry.rb
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/resources/psychrometrics.rb
  ReportUtilityBills/measure.xml
  workflow/tests/base_results/results_acca_hvac.csv
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_hvac.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
  workflow/tests/base_results/results_sizing.csv
Labels: refactor, priority low

#1843 Bugfix for non-integer number of occupants
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  HPXMLtoOpenStudio/tests/test_hotwater_appliance.rb
  HPXMLtoOpenStudio/tests/test_miscloads.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  docs/source/workflow_inputs.rst
  workflow/hpxml_inputs.json
  workflow/sample_files/base-hvac-autosize-sizing-controls.xml
  workflow/sample_files/base-residents-5-5.xml
  workflow/tests/ACCA_Examples/Long_Residence.xml
  workflow/tests/ACCA_Examples/Vatilo_Residence.xml
  workflow/tests/ACCA_Examples/Victor_Residence.xml
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_hvac.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
Labels: bug

#1844 Avoid CSV library for speed
  BuildResidentialScheduleFile/measure.xml
  BuildResidentialScheduleFile/resources/schedules.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/schedules.rb
  ReportSimulationOutput/measure.rb
  ReportSimulationOutput/measure.xml
  ReportUtilityBills/measure.rb
  ReportUtilityBills/measure.xml
Labels: performance

#1840 More ruby documentation; prototype general model.rb add methods
  BuildResidentialHPXML/README.md
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  BuildResidentialHPXML/resources/geometry.rb
  BuildResidentialScheduleFile/measure.rb
  BuildResidentialScheduleFile/measure.xml
  BuildResidentialScheduleFile/resources/schedules.rb
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/battery.rb
  HPXMLtoOpenStudio/resources/constants.rb
  HPXMLtoOpenStudio/resources/constructions.rb
  HPXMLtoOpenStudio/resources/defaults.rb
  HPXMLtoOpenStudio/resources/energyplus.rb
  HPXMLtoOpenStudio/resources/generator.rb
  HPXMLtoOpenStudio/resources/geometry.rb
  HPXMLtoOpenStudio/resources/hotwater_appliances.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/resources/internal_gains.rb
  HPXMLtoOpenStudio/resources/lighting.rb
  HPXMLtoOpenStudio/resources/location.rb
  HPXMLtoOpenStudio/resources/meta_measure.rb
  HPXMLtoOpenStudio/resources/misc_loads.rb
  HPXMLtoOpenStudio/resources/model.rb
  HPXMLtoOpenStudio/resources/output.rb
  HPXMLtoOpenStudio/resources/pv.rb
  HPXMLtoOpenStudio/resources/schedules.rb
  HPXMLtoOpenStudio/resources/waterheater.rb
  HPXMLtoOpenStudio/resources/weather.rb
  HPXMLtoOpenStudio/tests/test_airflow.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  HPXMLtoOpenStudio/tests/test_hvac.rb
  HPXMLtoOpenStudio/tests/test_schedules.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  HPXMLtoOpenStudio/tests/test_weather.rb
  HPXMLtoOpenStudio/tests/util.rb
  ReportUtilityBills/measure.xml
  ReportUtilityBills/tests/test_report_utility_bills.rb
  docs/source/workflow_inputs.rst
  tasks.rb
  workflow/run_simulation.rb
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
Labels: refactor, documentation
