Repository NREL/OpenStudio-HPXML, pull requests merged in 2024-04, with the labels that each got.

#1671 Slab bugfix
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/constructions.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/tests/test_validation.rb
Labels: bug

#1673 Docs footnote check
  .github/workflows/config.yml
Labels: documentation

#1661 Shared water heater updates
  Changelog.md
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/waterheater.rb
  HPXMLtoOpenStudio/tests/test_water_heater.rb
  docs/source/workflow_inputs.rst
  workflow/hpxml_inputs.json
  workflow/sample_files/base-bldgtype-mf-unit-shared-water-heater-heat-pump.xml
  workflow/tests/base_results/results_workflow_simulations1.csv
  workflow/tests/base_results/results_workflow_simulations1_bills.csv
Labels: bug, documentation

#1679 Slab gap insulation R-value input
  Changelog.md
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/tests/test_defaults.rb
  HPXMLtoOpenStudio/tests/test_enclosure.rb
  docs/source/images/slab.png
  docs/source/workflow_inputs.rst
  tasks.rb
  workflow/sample_files/base-foundation-slab.xml
  workflow/tests/base_results/results_workflow_simulations1.csv
  workflow/tests/base_results/results_workflow_simulations1_bills.csv
Labels: enhancement

#1684 Fix buried duct effective R-values
  Changelog.md
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/tests/test_airflow.rb
  docs/source/workflow_inputs.rst
  workflow/tests/base_results/results_simulations1_bills.csv
  workflow/tests/base_results/results_simulations1_energy.csv
  workflow/tests/base_results/results_simulations1_hvac.csv
  workflow/tests/base_results/results_simulations1_loads.csv
  workflow/tests/base_results/results_simulations1_misc.csv
  workflow/tests/base_results/results_sizing.csv
Labels: bug

#1686 Fix shared boiler default location
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  docs/source/workflow_inputs.rst
Labels: bug
