Repository NREL/OpenStudio-HPXML, pull requests merged in 2024-08, with the labels that each got.

#1795 Improve docs for geothermal loops
  docs/source/workflow_inputs.rst
Labels: documentation

#1789 Cleanup docs related to modeling whole MF buildings
  docs/source/intro.rst
  docs/source/usage_instructions.rst
  docs/source/workflow_inputs.rst
  docs/source/workflow_outputs.rst
Labels: documentation

#1798 BuildResidentialHPXML: clean up create_windows_and_skylights
  BuildResidentialHPXML/measure.xml
  BuildResidentialHPXML/resources/geometry.rb
  HPXMLtoOpenStudio/measure.xml
Labels: refactor

#1800 BuildResidentialHPXML: Clarifies window area inputs for adiabatic walls
  BuildResidentialHPXML/README.md
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
Labels: documentation

#1801 Refactor airflow timeseries outputs (for whole MF buildings)
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/constants.rb
  ReportSimulationOutput/measure.rb
  ReportSimulationOutput/measure.xml
Labels: performance, refactor

#1791 Fix scheduled battery w/unavailable period
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/data/unavailable_periods.csv
  HPXMLtoOpenStudio/resources/schedules.rb
  workflow/hpxml_inputs.json
  workflow/sample_files/base-battery-scheduled-power-outage.xml
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_hvac.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
Labels: bug

#1806 Update to HPXML v4.0-rc5
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml_schema/HPXML.xsd
Labels: enhancement

#1784 More ruby documentation
  BuildResidentialHPXML/README.md
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  BuildResidentialHPXML/resources/geometry.rb
  BuildResidentialScheduleFile/measure.rb
  BuildResidentialScheduleFile/measure.xml
  BuildResidentialScheduleFile/resources/README.md
  BuildResidentialScheduleFile/resources/constants.rb
  BuildResidentialScheduleFile/resources/schedules.csv
  BuildResidentialScheduleFile/resources/schedules.rb
  BuildResidentialScheduleFile/resources/schedules_config.md
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/battery.rb
  HPXMLtoOpenStudio/resources/data/default_schedules.csv
  HPXMLtoOpenStudio/resources/data/g_functions/util.rb
  HPXMLtoOpenStudio/resources/generator.rb
  HPXMLtoOpenStudio/resources/geometry.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/resources/location.rb
  HPXMLtoOpenStudio/resources/pv.rb
  HPXMLtoOpenStudio/resources/schedules.rb
  HPXMLtoOpenStudio/resources/simcontrols.rb
  HPXMLtoOpenStudio/resources/util.rb
  HPXMLtoOpenStudio/resources/version.rb
  HPXMLtoOpenStudio/resources/weather.rb
  HPXMLtoOpenStudio/resources/xmlhelper.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  HPXMLtoOpenStudio/tests/test_schedules.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  ReportUtilityBills/measure.rb
  ReportUtilityBills/measure.xml
  ReportUtilityBills/resources/util.rb
  docs/source/workflow_inputs.rst
  tasks.rb
Labels: documentation

#1810 Bug in create_apartment method
  BuildResidentialHPXML/measure.xml
  BuildResidentialHPXML/resources/geometry.rb
Labels: bug

#1761 Update hot water end uses for operational calculations
  BuildResidentialScheduleFile/measure.xml
  BuildResidentialScheduleFile/resources/schedules.rb
  Changelog.md
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/geometry.rb
  HPXMLtoOpenStudio/resources/hotwater_appliances.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/resources/schedules.rb
  HPXMLtoOpenStudio/tests/test_hotwater_appliance.rb
  ReportUtilityBills/measure.rb
  ReportUtilityBills/measure.xml
  docs/source/workflow_inputs.rst
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
Labels: enhancement

#1808 Refactor constants
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  BuildResidentialHPXML/resources/constants.rb
  BuildResidentialHPXML/resources/geometry.rb
  BuildResidentialHPXML/tests/test_build_residential_hpxml.rb
  BuildResidentialScheduleFile/measure.rb
  BuildResidentialScheduleFile/measure.xml
  BuildResidentialScheduleFile/resources/schedules.rb
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/battery.rb
  HPXMLtoOpenStudio/resources/calendar.rb
  HPXMLtoOpenStudio/resources/constants.rb
  HPXMLtoOpenStudio/resources/constructions.rb
  HPXMLtoOpenStudio/resources/energyplus.rb
  HPXMLtoOpenStudio/resources/geometry.rb
  HPXMLtoOpenStudio/resources/hotwater_appliances.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/resources/lighting.rb
  HPXMLtoOpenStudio/resources/materials.rb
  HPXMLtoOpenStudio/resources/math.rb
  HPXMLtoOpenStudio/resources/misc_loads.rb
  HPXMLtoOpenStudio/resources/output.rb
  HPXMLtoOpenStudio/resources/schedules.rb
  HPXMLtoOpenStudio/resources/utility_bills.rb
  HPXMLtoOpenStudio/resources/waterheater.rb
  HPXMLtoOpenStudio/resources/weather.rb
  HPXMLtoOpenStudio/tests/test_airflow.rb
  HPXMLtoOpenStudio/tests/test_battery.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  HPXMLtoOpenStudio/tests/test_enclosure.rb
  HPXMLtoOpenStudio/tests/test_generator.rb
  HPXMLtoOpenStudio/tests/test_hotwater_appliance.rb
  HPXMLtoOpenStudio/tests/test_hvac.rb
  HPXMLtoOpenStudio/tests/test_lighting.rb
  HPXMLtoOpenStudio/tests/test_location.rb
  HPXMLtoOpenStudio/tests/test_miscloads.rb
  HPXMLtoOpenStudio/tests/test_pv.rb
  HPXMLtoOpenStudio/tests/test_schedules.rb
  HPXMLtoOpenStudio/tests/test_simcontrols.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  HPXMLtoOpenStudio/tests/test_water_heater.rb
  HPXMLtoOpenStudio/tests/test_weather.rb
  ReportSimulationOutput/measure.rb
  ReportSimulationOutput/measure.xml
  ReportSimulationOutput/tests/test_report_sim_output.rb
  ReportUtilityBills/measure.rb
  ReportUtilityBills/measure.xml
  ReportUtilityBills/resources/util.rb
  ReportUtilityBills/tests/test_report_utility_bills.rb
  workflow/tests/util.rb
Labels: refactor

#1813 Fix link to neighbor docs in BuildResHPXML measure
  BuildResidentialHPXML/README.md
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
Labels: documentation

#1749 Adding slab exterior horizontal insulation feature
  BuildResidentialHPXML/README.md
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  BuildResidentialHPXML/tests/test_build_residential_hpxml.rb
  Changelog.md
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/constructions.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hpxml_schema/HPXML.xsd
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  HPXMLtoOpenStudio/tests/test_enclosure.rb
  HPXMLtoOpenStudio/tests/test_hvac_sizing.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  docs/source/images/slab.png
  docs/source/workflow_inputs.rst
  tasks.rb
  workflow/hpxml_inputs.json
  workflow/sample_files/base-foundation-slab-exterior-horizontal-insulation.xml
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_hvac.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
Labels: enhancement, hpxml
