Repository NREL/OpenStudio-HPXML, pull requests merged in 2024-05, with the labels that each got.

#1700 Add documentation for reduced attic floor insulation at the eaves
  docs/source/workflow_inputs.rst
Labels: documentation

#1630 OpenStudio 3.8/EnergyPlus 24.1
  .github/workflows/config.yml
  .rubocop.yml
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  BuildResidentialHPXML/resources/geometry.rb
  BuildResidentialHPXML/tests/test_build_residential_hpxml.rb
  BuildResidentialScheduleFile/measure.rb
  BuildResidentialScheduleFile/measure.xml
  Changelog.md
  Gemfile
  Gemfile.lock
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/geometry.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/meta_measure.rb
  HPXMLtoOpenStudio/resources/util.rb
  HPXMLtoOpenStudio/resources/version.rb
  ReportSimulationOutput/measure.rb
  ReportSimulationOutput/measure.xml
  ReportUtilityBills/measure.rb
  ReportUtilityBills/measure.xml
  docs/source/usage_instructions.rst
  tasks.rb
Labels: enhancement, openstudio, energyplus

#1576 Replace EC_adj EMS program
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/constants.rb
  HPXMLtoOpenStudio/resources/waterheater.rb
  HPXMLtoOpenStudio/tests/test_water_heater.rb
  ReportSimulationOutput/measure.rb
  ReportSimulationOutput/measure.xml
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
  workflow/tests/util.rb
Labels: energyplus, refactor

#1215 Component loads alternative
  Changelog.md
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  workflow/tests/base_results/results_simulations_loads.csv
Labels: enhancement, refactor

#1710 Update usage_instructions.rst
  docs/source/usage_instructions.rst
Labels: documentation

#1713 Misc hpxml.rb cleanup
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  tasks.rb
  workflow/tests/util.rb
Labels: refactor

#1705 Zone design loads
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  Changelog.md
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/constants.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/resources/output.rb
  HPXMLtoOpenStudio/tests/test_hvac_sizing.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  ReportSimulationOutput/measure.xml
  ReportUtilityBills/measure.xml
  docs/source/workflow_inputs.rst
  docs/source/workflow_outputs.rst
  tasks.rb
  workflow/hpxml_inputs.json
  workflow/real_homes/house045.xml
  workflow/sample_files/base-enclosure-skylights-cathedral.xml
  workflow/sample_files/base-enclosure-skylights-physical-properties.xml
  workflow/sample_files/base-enclosure-skylights-shading.xml
  workflow/sample_files/base-enclosure-skylights-storms.xml
  workflow/sample_files/base-enclosure-skylights.xml
  workflow/sample_files/base-zones-spaces-multiple.xml
  workflow/sample_files/base-zones-spaces.xml
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_hvac.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
  workflow/tests/base_results/results_sizing.csv
  workflow/tests/util.rb
Labels: enhancement

#1689 Adds geothermal loop outputs to annual results file
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/resources/output.rb
  HPXMLtoOpenStudio/resources/utility_bills.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  ReportSimulationOutput/measure.xml
  ReportSimulationOutput/tests/test_report_sim_output.rb
  docs/source/workflow_inputs.rst
  docs/source/workflow_outputs.rst
  workflow/hpxml_inputs.json
  workflow/sample_files/base-hvac-ground-to-air-heat-pump-detailed-geothermal-loop.xml
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
  workflow/tests/util.rb
Labels: enhancement

#1693 Default shielding for SFA/MF
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/hpxml_defaults.rb
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  docs/source/workflow_inputs.rst
  workflow/tests/ACCA_Examples/Bell_Residence.xml
  workflow/tests/ACCA_Examples/Cobb_Residence.xml
  workflow/tests/ACCA_Examples/Long_Residence.xml
  workflow/tests/ACCA_Examples/Smith_Residence.xml
  workflow/tests/ACCA_Examples/Vatilo_Residence.xml
  workflow/tests/ACCA_Examples/Victor_Residence.xml
  workflow/tests/ACCA_Examples/Walker_Residence.xml
  workflow/tests/base_results/results_hers_hvac.csv
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_hvac.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
  workflow/tests/base_results/results_sizing.csv
  workflow/tests/util.rb
Labels: enhancement

#1718 Skylight bugfix
  Changelog.md
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/tests/test_validation.rb
  docs/source/workflow_inputs.rst
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
Labels: bug

#1725 Ductless MSHP w/integrated backup and advanced defrost throws error
  HPXMLtoOpenStudio/resources/hvac.rb
  workflow/hpxml_inputs.json
  workflow/sample_files/base-hvac-mini-split-heat-pump-ductless-backup-advanced-defrost.xml
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_hvac.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
  workflow/tests/base_results/results_sizing.csv
Labels: bug

#1729 Allow rounding msgpack timeseries output
  ReportSimulationOutput/README.md
  ReportSimulationOutput/measure.rb
  ReportSimulationOutput/measure.xml
Labels: enhancement

#1733 Bugfix related to collapsing skylight surfaces
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml.rb
Labels: bug

#1735 Slab AttachedToSpace schematron bugfix
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/tests/test_validation.rb
Labels: bug
