Repository NREL/OpenStudio-HPXML, pull requests merged in 2025-03, with the labels that each got.

#1932 Add heat pump pan heater inputs
  BuildResidentialHPXML/README.md
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/constants.rb
  HPXMLtoOpenStudio/resources/defaults.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  HPXMLtoOpenStudio/tests/test_hvac.rb
  ReportSimulationOutput/measure.rb
  ReportSimulationOutput/measure.xml
  docs/source/workflow_inputs.rst
  workflow/hpxml_inputs.json
  workflow/sample_files/base-hvac-air-to-air-heat-pump-var-speed-pan-heater-continuous-mode.xml
  workflow/sample_files/base-hvac-air-to-air-heat-pump-var-speed-pan-heater-defrost-mode.xml
  workflow/sample_files/base-hvac-air-to-air-heat-pump-var-speed-pan-heater-none.xml
  workflow/tests/base_results/results_hers_hvac.csv
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_hvac.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
  workflow/tests/base_results/results_sizing.csv
  workflow/tests/util.rb
Labels: enhancement

#1941 Speed up weather processing
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  BuildResidentialScheduleFile/measure.rb
  BuildResidentialScheduleFile/measure.xml
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/data/Xing_okstate_0664D_13659_Table_A-3.csv
  HPXMLtoOpenStudio/resources/defaults.rb
  HPXMLtoOpenStudio/resources/location.rb
  HPXMLtoOpenStudio/resources/output.rb
  HPXMLtoOpenStudio/resources/weather.rb
  HPXMLtoOpenStudio/tests/test_location.rb
  HPXMLtoOpenStudio/tests/test_weather.rb
Labels: performance, refactor

#1934 BuildResidentialHPXML measure: Fix shared combi boiler error
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  Changelog.md
  workflow/hpxml_inputs.json
  workflow/sample_files/base-bldgtype-mf-unit-shared-boiler-only-baseboard-combi-tankless.xml
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_hvac.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
Labels: bug

#1944 Smooth schedule for plugload ev
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/data/default_schedules.csv
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_misc.csv
Labels: enhancement

#1953 Fixes default solar screen/film coefficients
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/defaults.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  docs/source/workflow_inputs.rst
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
Labels: bug

#1936 Update 1- and 2-speed AC/HP models
  BuildResidentialHPXML/README.md
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  BuildResidentialHPXML/tests/test_build_residential_hpxml.rb
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/defaults.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/resources/math.rb
  HPXMLtoOpenStudio/resources/model.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  HPXMLtoOpenStudio/tests/test_hvac.rb
  HPXMLtoOpenStudio/tests/test_hvac_sizing.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  docs/source/workflow_inputs.rst
  tasks.rb
  workflow/hpxml_inputs.json
  workflow/sample_files/base-hvac-air-to-air-heat-pump-1-speed-detailed-performance.xml
  workflow/sample_files/base-hvac-air-to-air-heat-pump-2-speed-detailed-performance.xml
  workflow/sample_files/base-hvac-central-ac-only-1-speed-detailed-performance.xml
  workflow/sample_files/base-hvac-central-ac-only-2-speed-detailed-performance.xml
  workflow/template-build-and-run-hpxml-with-stochastic-occupancy.osw
  workflow/tests/base_results/results_acca_hvac.csv
  workflow/tests/base_results/results_hers_dse.csv
  workflow/tests/base_results/results_hers_hvac.csv
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_hvac.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
  workflow/tests/base_results/results_sizing.csv
  workflow/tests/test_hers.rb
Labels: enhancement

#1971 Fix error if vented attic w/ zero pitch
  BuildResidentialHPXML/measure.xml
  BuildResidentialHPXML/resources/geometry.rb
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/constructions.rb
  HPXMLtoOpenStudio/resources/geometry.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/materials.rb
  HPXMLtoOpenStudio/tests/test_airflow.rb
  HPXMLtoOpenStudio/tests/test_enclosure.rb
  workflow/tests/base_results/results_hers_hot_water.csv
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
Labels: bug
