Repository NREL/OpenStudio-HPXML, pull requests merged in 2025-02, with the labels that each got.

#1918 Timeseries EnergyPlus output meters
  Changelog.md
  ReportSimulationOutput/README.md
  ReportSimulationOutput/measure.rb
  ReportSimulationOutput/measure.xml
  ReportSimulationOutput/tests/test_report_sim_output.rb
  docs/source/usage_instructions.rst
  docs/source/workflow_outputs.rst
  workflow/run_simulation.rb
  workflow/template-build-and-run-hpxml-with-stochastic-occupancy.osw
  workflow/template-run-hpxml-with-stochastic-occupancy-subset.osw
  workflow/template-run-hpxml-with-stochastic-occupancy.osw
  workflow/template-run-hpxml.osw
  workflow/tests/test_other.rb
Labels: enhancement

#1919 HPXML class: Allow multiple program versions
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/defaults.rb
  HPXMLtoOpenStudio/resources/hotwater_appliances.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/lighting.rb
  HPXMLtoOpenStudio/resources/waterheater.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
Labels: enhancement, refactor

#1921 Fix unavailable period less than 24 hours
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/schedules.rb
  HPXMLtoOpenStudio/tests/test_schedules.rb
Labels: bug

#1922 Change temperature capacitance multiplier argument from string to double
  BuildResidentialHPXML/README.md
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
Labels: bug

#1915 Generate schedules only for things that exist
  BuildResidentialScheduleFile/resources/schedules.rb
  BuildResidentialScheduleFile/tests/test_build_residential_schedule_file.rb
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic-10-mins.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic-30-mins.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic-ev-charger.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic_2.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic_3.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic_4.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic_5.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic_6.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic_mf.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic_mf_2.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic_mf_3.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic_mf_4.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic_mf_5.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic_mf_6.csv
  HPXMLtoOpenStudio/tests/test_schedules.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  tasks.rb
  workflow/hpxml_inputs.json
  workflow/sample_files/base-bldgtype-mf-whole-building.xml
  workflow/sample_files/base-vehicle-stochastic.xml
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_hvac.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
Labels: enhancement

#1757 Generate EV schedules
  .github/workflows/config.yml
  BuildResidentialScheduleFile/measure.rb
  BuildResidentialScheduleFile/measure.xml
  BuildResidentialScheduleFile/resources/schedules.rb
  BuildResidentialScheduleFile/tests/test_build_residential_schedule_file.rb
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic-10-mins.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic-30-mins.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic-ev-charger.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic-mf-unit.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic-mf-unit_2.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic-mf-unit_3.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic-mf-unit_4.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic-mf-unit_5.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic-mf-unit_6.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic_2.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic_3.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic_4.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic_5.csv
  HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic_6.csv
  HPXMLtoOpenStudio/resources/schedules.rb
  HPXMLtoOpenStudio/tests/test_schedules.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  docs/source/workflow_inputs.rst
  tasks.rb
  workflow/hpxml_inputs.json
  workflow/run_simulation.rb
  workflow/sample_files/base-bldgtype-mf-whole-building.xml
  workflow/sample_files/base-vehicle-ev-charger-occupancy-stochastic.xml
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_hvac.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
Labels: enhancement

#1933 Fix stochastic schedule generation runtime
  BuildResidentialHPXML/measure.rb
  BuildResidentialHPXML/measure.xml
  BuildResidentialHPXML/resources/geometry.rb
  BuildResidentialScheduleFile/measure.rb
  BuildResidentialScheduleFile/measure.xml
  BuildResidentialScheduleFile/resources/schedules.rb
  HPXMLtoOpenStudio/measure.xml
  ReportSimulationOutput/measure.xml
  ReportSimulationOutput/tests/test_report_sim_output.rb
Labels: performance

#1938 Fixes possible hvac sizing error
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml.rb
  tasks.rb
  workflow/hpxml_inputs.json
  workflow/sample_files/base-bldgtype-mf-unit-adjacent-to-other-housing-unit-basement.xml
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_hvac.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
Labels: bug
