Repository NREL/OpenStudio-HPXML, pull requests merged in 2025-04, with the labels that each got.

#1964 HVAC design airflow rates
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  HPXMLtoOpenStudio/tests/test_hvac.rb
  docs/source/workflow_inputs.rst
  workflow/tests/base_results/results_acca_hvac.csv
  workflow/tests/base_results/results_hers_dse.csv
  workflow/tests/base_results/results_hers_hvac.csv
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_hvac.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
  workflow/tests/base_results/results_sizing.csv
  workflow/tests/util.rb
Labels: enhancement

#1972 Clarify peak outputs with respect to simulation timestep in docs
  docs/source/workflow_outputs.rst
Labels: documentation

#1973 Fix handling user output requests with 'none' timeseries frequency
  ReportSimulationOutput/measure.rb
  ReportSimulationOutput/measure.xml
  ReportSimulationOutput/tests/test_report_sim_output.rb
Labels: bug

#1979 HVAC design airflow rate inputs
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/defaults.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/resources/hvac_sizing.rb
  HPXMLtoOpenStudio/tests/test_hvac.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  docs/source/workflow_inputs.rst
  tasks.rb
  workflow/sample_files/base-hvac-install-quality-air-to-air-heat-pump-1-speed.xml
  workflow/sample_files/base-hvac-install-quality-air-to-air-heat-pump-2-speed.xml
  workflow/sample_files/base-hvac-install-quality-air-to-air-heat-pump-var-speed-detailed-performance.xml
  workflow/sample_files/base-hvac-install-quality-air-to-air-heat-pump-var-speed.xml
  workflow/sample_files/base-hvac-install-quality-furnace-gas-central-ac-1-speed.xml
  workflow/sample_files/base-hvac-install-quality-furnace-gas-central-ac-2-speed.xml
  workflow/sample_files/base-hvac-install-quality-furnace-gas-central-ac-var-speed.xml
  workflow/sample_files/base-hvac-install-quality-furnace-gas-only.xml
  workflow/sample_files/base-hvac-install-quality-ground-to-air-heat-pump.xml
  workflow/sample_files/base-hvac-install-quality-mini-split-air-conditioner-only-ducted.xml
  workflow/sample_files/base-hvac-install-quality-mini-split-heat-pump-ducted.xml
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
Labels: enhancement

#1981 Small geometry refactor
  HPXMLtoOpenStudio/measure.rb
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/airflow.rb
  HPXMLtoOpenStudio/resources/geometry.rb
Labels: refactor

#1984 `EquipmentType` input for central ACs/ASHPs
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/defaults.rb
  HPXMLtoOpenStudio/resources/hpxml.rb
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/resources/hvac.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  docs/source/workflow_inputs.rst
  tasks.rb
  workflow/hpxml_inputs.json
  workflow/sample_files/base-hvac-air-to-air-heat-pump-1-speed-space-constrained.xml
  workflow/sample_files/base-hvac-central-ac-only-1-speed-space-constrained.xml
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_hvac.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
  workflow/tests/base_results/results_sizing.csv
Labels: enhancement

#1988 Refactor BuildResidentialScheduleFile measure to use the HPXML class
  BuildResidentialScheduleFile/measure.rb
  BuildResidentialScheduleFile/measure.xml
  BuildResidentialScheduleFile/tests/test_build_residential_schedule_file.rb
  tasks.rb
  workflow/run_simulation.rb
Labels: refactor

#1992 TankModelType=stratified bugfixes
  Changelog.md
  HPXMLtoOpenStudio/measure.xml
  HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
  HPXMLtoOpenStudio/resources/waterheater.rb
  HPXMLtoOpenStudio/tests/test_defaults.rb
  HPXMLtoOpenStudio/tests/test_validation.rb
  HPXMLtoOpenStudio/tests/test_water_heater.rb
  docs/source/workflow_inputs.rst
  workflow/tests/base_results/results_simulations_bills.csv
  workflow/tests/base_results/results_simulations_energy.csv
  workflow/tests/base_results/results_simulations_loads.csv
  workflow/tests/base_results/results_simulations_misc.csv
Labels: bug

#1998 Refactor BuildResidentialScheduleFile measure to use the HPXML class, take 3
  BuildResidentialScheduleFile/measure.rb
  BuildResidentialScheduleFile/measure.xml
  BuildResidentialScheduleFile/tests/test_build_residential_schedule_file.rb
Labels: bug
